<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (Schema::hasTable('cities')) {
            $datas = [
                        [null, '11', 'KABUPATEN SIMEULUE'],
                        [null, '11', 'KABUPATEN ACEH SINGKIL'],
                        [null, '11', 'KABUPATEN ACEH SELATAN'],
                        [null, '11', 'KABUPATEN ACEH TENGGARA'],
                        [null, '11', 'KABUPATEN ACEH TIMUR'],
                        [null, '11', 'KABUPATEN ACEH TENGAH'],
                        [null, '11', 'KABUPATEN ACEH BARAT'],
                        [null, '11', 'KABUPATEN ACEH BESAR'],
                        [null, '11', 'KABUPATEN PIDIE'],
                        [null, '11', 'KABUPATEN BIREUEN'],
                        [null, '11', 'KABUPATEN ACEH UTARA'],
                        [null, '11', 'KABUPATEN ACEH BARAT DAYA'],
                        [null, '11', 'KABUPATEN GAYO LUES'],
                        [null, '11', 'KABUPATEN ACEH TAMIANG'],
                        [null, '11', 'KABUPATEN NAGAN RAYA'],
                        [null, '11', 'KABUPATEN ACEH JAYA'],
                        [null, '11', 'KABUPATEN BENER MERIAH'],
                        [null, '11', 'KABUPATEN PIDIE JAYA'],
                        [null, '11', 'KOTA BANDA ACEH'],
                        [null, '11', 'KOTA SABANG'],
                        [null, '11', 'KOTA LANGSA'],
                        [null, '11', 'KOTA LHOKSEUMAWE'],
                        [null, '11', 'KOTA SUBULUSSALAM'],
                        [null, '12', 'KABUPATEN NIAS'],
                        [null, '12', 'KABUPATEN MANDAILING NATAL'],
                        [null, '12', 'KABUPATEN TAPANULI SELATAN'],
                        [null, '12', 'KABUPATEN TAPANULI TENGAH'],
                        [null, '12', 'KABUPATEN TAPANULI UTARA'],
                        [null, '12', 'KABUPATEN TOBA SAMOSIR'],
                        [null, '12', 'KABUPATEN LABUHAN BATU'],
                        [null, '12', 'KABUPATEN ASAHAN'],
                        [null, '12', 'KABUPATEN SIMALUNGUN'],
                        [null, '12', 'KABUPATEN DAIRI'],
                        [null, '12', 'KABUPATEN KARO'],
                        [null, '12', 'KABUPATEN DELI SERDANG'],
                        [null, '12', 'KABUPATEN LANGKAT'],
                        [null, '12', 'KABUPATEN NIAS SELATAN'],
                        [null, '12', 'KABUPATEN HUMBANG HASUNDUTAN'],
                        [null, '12', 'KABUPATEN PAKPAK BHARAT'],
                        [null, '12', 'KABUPATEN SAMOSIR'],
                        [null, '12', 'KABUPATEN SERDANG BEDAGAI'],
                        [null, '12', 'KABUPATEN BATU BARA'],
                        [null, '12', 'KABUPATEN PADANG LAWAS UTARA'],
                        [null, '12', 'KABUPATEN PADANG LAWAS'],
                        [null, '12', 'KABUPATEN LABUHAN BATU SELATAN'],
                        [null, '12', 'KABUPATEN LABUHAN BATU UTARA'],
                        [null, '12', 'KABUPATEN NIAS UTARA'],
                        [null, '12', 'KABUPATEN NIAS BARAT'],
                        [null, '12', 'KOTA SIBOLGA'],
                        [null, '12', 'KOTA TANJUNG BALAI'],
                        [null, '12', 'KOTA PEMATANG SIANTAR'],
                        [null, '12', 'KOTA TEBING TINGGI'],
                        [null, '12', 'KOTA MEDAN'],
                        [null, '12', 'KOTA BINJAI'],
                        [null, '12', 'KOTA PADANGSIDIMPUAN'],
                        [null, '12', 'KOTA GUNUNGSITOLI'],
                        [null, '13', 'KABUPATEN KEPULAUAN MENTAWAI'],
                        [null, '13', 'KABUPATEN PESISIR SELATAN'],
                        [null, '13', 'KABUPATEN SOLOK'],
                        [null, '13', 'KABUPATEN SIJUNJUNG'],
                        [null, '13', 'KABUPATEN TANAH DATAR'],
                        [null, '13', 'KABUPATEN PADANG PARIAMAN'],
                        [null, '13', 'KABUPATEN AGAM'],
                        [null, '13', 'KABUPATEN LIMA PULUH KOTA'],
                        [null, '13', 'KABUPATEN PASAMAN'],
                        [null, '13', 'KABUPATEN SOLOK SELATAN'],
                        [null, '13', 'KABUPATEN DHARMASRAYA'],
                        [null, '13', 'KABUPATEN PASAMAN BARAT'],
                        [null, '13', 'KOTA PADANG'],
                        [null, '13', 'KOTA SOLOK'],
                        [null, '13', 'KOTA SAWAH LUNTO'],
                        [null, '13', 'KOTA PADANG PANJANG'],
                        [null, '13', 'KOTA BUKITTINGGI'],
                        [null, '13', 'KOTA PAYAKUMBUH'],
                        [null, '13', 'KOTA PARIAMAN'],
                        [null, '14', 'KABUPATEN KUANTAN SINGINGI'],
                        [null, '14', 'KABUPATEN INDRAGIRI HULU'],
                        [null, '14', 'KABUPATEN INDRAGIRI HILIR'],
                        [null, '14', 'KABUPATEN PELALAWAN'],
                        [null, '14', 'KABUPATEN S I A K'],
                        [null, '14', 'KABUPATEN KAMPAR'],
                        [null, '14', 'KABUPATEN ROKAN HULU'],
                        [null, '14', 'KABUPATEN BENGKALIS'],
                        [null, '14', 'KABUPATEN ROKAN HILIR'],
                        [null, '14', 'KABUPATEN KEPULAUAN MERANTI'],
                        [null, '14', 'KOTA PEKANBARU'],
                        [null, '14', 'KOTA D U M A I'],
                        [null, '15', 'KABUPATEN KERINCI'],
                        [null, '15', 'KABUPATEN MERANGIN'],
                        [null, '15', 'KABUPATEN SAROLANGUN'],
                        [null, '15', 'KABUPATEN BATANG HARI'],
                        [null, '15', 'KABUPATEN MUARO JAMBI'],
                        [null, '15', 'KABUPATEN TANJUNG JABUNG TIMUR'],
                        [null, '15', 'KABUPATEN TANJUNG JABUNG BARAT'],
                        [null, '15', 'KABUPATEN TEBO'],
                        [null, '15', 'KABUPATEN BUNGO'],
                        [null, '15', 'KOTA JAMBI'],
                        [null, '15', 'KOTA SUNGAI PENUH'],
                        [null, '16', 'KABUPATEN OGAN KOMERING ULU'],
                        [null, '16', 'KABUPATEN OGAN KOMERING ILIR'],
                        [null, '16', 'KABUPATEN MUARA ENIM'],
                        [null, '16', 'KABUPATEN LAHAT'],
                        [null, '16', 'KABUPATEN MUSI RAWAS'],
                        [null, '16', 'KABUPATEN MUSI BANYUASIN'],
                        [null, '16', 'KABUPATEN BANYU ASIN'],
                        [null, '16', 'KABUPATEN OGAN KOMERING ULU SELATAN'],
                        [null, '16', 'KABUPATEN OGAN KOMERING ULU TIMUR'],
                        [null, '16', 'KABUPATEN OGAN ILIR'],
                        [null, '16', 'KABUPATEN EMPAT LAWANG'],
                        [null, '16', 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
                        [null, '16', 'KABUPATEN MUSI RAWAS UTARA'],
                        [null, '16', 'KOTA PALEMBANG'],
                        [null, '16', 'KOTA PRABUMULIH'],
                        [null, '16', 'KOTA PAGAR ALAM'],
                        [null, '16', 'KOTA LUBUKLINGGAU'],
                        [null, '17', 'KABUPATEN BENGKULU SELATAN'],
                        [null, '17', 'KABUPATEN REJANG LEBONG'],
                        [null, '17', 'KABUPATEN BENGKULU UTARA'],
                        [null, '17', 'KABUPATEN KAUR'],
                        [null, '17', 'KABUPATEN SELUMA'],
                        [null, '17', 'KABUPATEN MUKOMUKO'],
                        [null, '17', 'KABUPATEN LEBONG'],
                        [null, '17', 'KABUPATEN KEPAHIANG'],
                        [null, '17', 'KABUPATEN BENGKULU TENGAH'],
                        [null, '17', 'KOTA BENGKULU'],
                        [null, '18', 'KABUPATEN LAMPUNG BARAT'],
                        [null, '18', 'KABUPATEN TANGGAMUS'],
                        [null, '18', 'KABUPATEN LAMPUNG SELATAN'],
                        [null, '18', 'KABUPATEN LAMPUNG TIMUR'],
                        [null, '18', 'KABUPATEN LAMPUNG TENGAH'],
                        [null, '18', 'KABUPATEN LAMPUNG UTARA'],
                        [null, '18', 'KABUPATEN WAY KANAN'],
                        [null, '18', 'KABUPATEN TULANGBAWANG'],
                        [null, '18', 'KABUPATEN PESAWARAN'],
                        [null, '18', 'KABUPATEN PRINGSEWU'],
                        [null, '18', 'KABUPATEN MESUJI'],
                        [null, '18', 'KABUPATEN TULANG BAWANG BARAT'],
                        [null, '18', 'KABUPATEN PESISIR BARAT'],
                        [null, '18', 'KOTA BANDAR LAMPUNG'],
                        [null, '18', 'KOTA METRO'],
                        [null, '19', 'KABUPATEN BANGKA'],
                        [null, '19', 'KABUPATEN BELITUNG'],
                        [null, '19', 'KABUPATEN BANGKA BARAT'],
                        [null, '19', 'KABUPATEN BANGKA TENGAH'],
                        [null, '19', 'KABUPATEN BANGKA SELATAN'],
                        [null, '19', 'KABUPATEN BELITUNG TIMUR'],
                        [null, '19', 'KOTA PANGKAL PINANG'],
                        [null, '21', 'KABUPATEN KARIMUN'],
                        [null, '21', 'KABUPATEN BINTAN'],
                        [null, '21', 'KABUPATEN NATUNA'],
                        [null, '21', 'KABUPATEN LINGGA'],
                        [null, '21', 'KABUPATEN KEPULAUAN ANAMBAS'],
                        [null, '21', 'KOTA BATAM'],
                        [null, '21', 'KOTA TANJUNG PINANG'],
                        [null, '31', 'KABUPATEN KEPULAUAN SERIBU'],
                        [null, '31', 'KOTA JAKARTA SELATAN'],
                        [null, '31', 'KOTA JAKARTA TIMUR'],
                        [null, '31', 'KOTA JAKARTA PUSAT'],
                        [null, '31', 'KOTA JAKARTA BARAT'],
                        [null, '31', 'KOTA JAKARTA UTARA'],
                        [null, '32', 'KABUPATEN BOGOR'],
                        [null, '32', 'KABUPATEN SUKABUMI'],
                        [null, '32', 'KABUPATEN CIANJUR'],
                        [null, '32', 'KABUPATEN BANDUNG'],
                        [null, '32', 'KABUPATEN GARUT'],
                        [null, '32', 'KABUPATEN TASIKMALAYA'],
                        [null, '32', 'KABUPATEN CIAMIS'],
                        [null, '32', 'KABUPATEN KUNINGAN'],
                        [null, '32', 'KABUPATEN CIREBON'],
                        [null, '32', 'KABUPATEN MAJALENGKA'],
                        [null, '32', 'KABUPATEN SUMEDANG'],
                        [null, '32', 'KABUPATEN INDRAMAYU'],
                        [null, '32', 'KABUPATEN SUBANG'],
                        [null, '32', 'KABUPATEN PURWAKARTA'],
                        [null, '32', 'KABUPATEN KARAWANG'],
                        [null, '32', 'KABUPATEN BEKASI'],
                        [null, '32', 'KABUPATEN BANDUNG BARAT'],
                        [null, '32', 'KABUPATEN PANGANDARAN'],
                        [null, '32', 'KOTA BOGOR'],
                        [null, '32', 'KOTA SUKABUMI'],
                        [null, '32', 'KOTA BANDUNG'],
                        [null, '32', 'KOTA CIREBON'],
                        [null, '32', 'KOTA BEKASI'],
                        [null, '32', 'KOTA DEPOK'],
                        [null, '32', 'KOTA CIMAHI'],
                        [null, '32', 'KOTA TASIKMALAYA'],
                        [null, '32', 'KOTA BANJAR'],
                        [null, '33', 'KABUPATEN CILACAP'],
                        [null, '33', 'KABUPATEN BANYUMAS'],
                        [null, '33', 'KABUPATEN PURBALINGGA'],
                        [null, '33', 'KABUPATEN BANJARNEGARA'],
                        [null, '33', 'KABUPATEN KEBUMEN'],
                        [null, '33', 'KABUPATEN PURWOREJO'],
                        [null, '33', 'KABUPATEN WONOSOBO'],
                        [null, '33', 'KABUPATEN MAGELANG'],
                        [null, '33', 'KABUPATEN BOYOLALI'],
                        [null, '33', 'KABUPATEN KLATEN'],
                        [null, '33', 'KABUPATEN SUKOHARJO'],
                        [null, '33', 'KABUPATEN WONOGIRI'],
                        [null, '33', 'KABUPATEN KARANGANYAR'],
                        [null, '33', 'KABUPATEN SRAGEN'],
                        [null, '33', 'KABUPATEN GROBOGAN'],
                        [null, '33', 'KABUPATEN BLORA'],
                        [null, '33', 'KABUPATEN REMBANG'],
                        [null, '33', 'KABUPATEN PATI'],
                        [null, '33', 'KABUPATEN KUDUS'],
                        [null, '33', 'KABUPATEN JEPARA'],
                        [null, '33', 'KABUPATEN DEMAK'],
                        [null, '33', 'KABUPATEN SEMARANG'],
                        [null, '33', 'KABUPATEN TEMANGGUNG'],
                        [null, '33', 'KABUPATEN KENDAL'],
                        [null, '33', 'KABUPATEN BATANG'],
                        [null, '33', 'KABUPATEN PEKALONGAN'],
                        [null, '33', 'KABUPATEN PEMALANG'],
                        [null, '33', 'KABUPATEN TEGAL'],
                        [null, '33', 'KABUPATEN BREBES'],
                        [null, '33', 'KOTA MAGELANG'],
                        [null, '33', 'KOTA SURAKARTA'],
                        [null, '33', 'KOTA SALATIGA'],
                        [null, '33', 'KOTA SEMARANG'],
                        [null, '33', 'KOTA PEKALONGAN'],
                        [null, '33', 'KOTA TEGAL'],
                        [null, '34', 'KABUPATEN KULON PROGO'],
                        [null, '34', 'KABUPATEN BANTUL'],
                        [null, '34', 'KABUPATEN GUNUNG KIDUL'],
                        [null, '34', 'KABUPATEN SLEMAN'],
                        [null, '34', 'KOTA YOGYAKARTA'],
                        [null, '35', 'KABUPATEN PACITAN'],
                        [null, '35', 'KABUPATEN PONOROGO'],
                        [null, '35', 'KABUPATEN TRENGGALEK'],
                        [null, '35', 'KABUPATEN TULUNGAGUNG'],
                        [null, '35', 'KABUPATEN BLITAR'],
                        [null, '35', 'KABUPATEN KEDIRI'],
                        [null, '35', 'KABUPATEN MALANG'],
                        [null, '35', 'KABUPATEN LUMAJANG'],
                        [null, '35', 'KABUPATEN JEMBER'],
                        [null, '35', 'KABUPATEN BANYUWANGI'],
                        [null, '35', 'KABUPATEN BONDOWOSO'],
                        [null, '35', 'KABUPATEN SITUBONDO'],
                        [null, '35', 'KABUPATEN PROBOLINGGO'],
                        [null, '35', 'KABUPATEN PASURUAN'],
                        [null, '35', 'KABUPATEN SIDOARJO'],
                        [null, '35', 'KABUPATEN MOJOKERTO'],
                        [null, '35', 'KABUPATEN JOMBANG'],
                        [null, '35', 'KABUPATEN NGANJUK'],
                        [null, '35', 'KABUPATEN MADIUN'],
                        [null, '35', 'KABUPATEN MAGETAN'],
                        [null, '35', 'KABUPATEN NGAWI'],
                        [null, '35', 'KABUPATEN BOJONEGORO'],
                        [null, '35', 'KABUPATEN TUBAN'],
                        [null, '35', 'KABUPATEN LAMONGAN'],
                        [null, '35', 'KABUPATEN GRESIK'],
                        [null, '35', 'KABUPATEN BANGKALAN'],
                        [null, '35', 'KABUPATEN SAMPANG'],
                        [null, '35', 'KABUPATEN PAMEKASAN'],
                        [null, '35', 'KABUPATEN SUMENEP'],
                        [null, '35', 'KOTA KEDIRI'],
                        [null, '35', 'KOTA BLITAR'],
                        [null, '35', 'KOTA MALANG'],
                        [null, '35', 'KOTA PROBOLINGGO'],
                        [null, '35', 'KOTA PASURUAN'],
                        [null, '35', 'KOTA MOJOKERTO'],
                        [null, '35', 'KOTA MADIUN'],
                        [null, '35', 'KOTA SURABAYA'],
                        [null, '35', 'KOTA BATU'],
                        [null, '36', 'KABUPATEN PANDEGLANG'],
                        [null, '36', 'KABUPATEN LEBAK'],
                        [null, '36', 'KABUPATEN TANGERANG'],
                        [null, '36', 'KABUPATEN SERANG'],
                        [null, '36', 'KOTA TANGERANG'],
                        [null, '36', 'KOTA CILEGON'],
                        [null, '36', 'KOTA SERANG'],
                        [null, '36', 'KOTA TANGERANG SELATAN'],
                        [null, '51', 'KABUPATEN JEMBRANA'],
                        [null, '51', 'KABUPATEN TABANAN'],
                        [null, '51', 'KABUPATEN BADUNG'],
                        [null, '51', 'KABUPATEN GIANYAR'],
                        [null, '51', 'KABUPATEN KLUNGKUNG'],
                        [null, '51', 'KABUPATEN BANGLI'],
                        [null, '51', 'KABUPATEN KARANG ASEM'],
                        [null, '51', 'KABUPATEN BULELENG'],
                        [null, '51', 'KOTA DENPASAR'],
                        [null, '52', 'KABUPATEN LOMBOK BARAT'],
                        [null, '52', 'KABUPATEN LOMBOK TENGAH'],
                        [null, '52', 'KABUPATEN LOMBOK TIMUR'],
                        [null, '52', 'KABUPATEN SUMBAWA'],
                        [null, '52', 'KABUPATEN DOMPU'],
                        [null, '52', 'KABUPATEN BIMA'],
                        [null, '52', 'KABUPATEN SUMBAWA BARAT'],
                        [null, '52', 'KABUPATEN LOMBOK UTARA'],
                        [null, '52', 'KOTA MATARAM'],
                        [null, '52', 'KOTA BIMA'],
                        [null, '53', 'KABUPATEN SUMBA BARAT'],
                        [null, '53', 'KABUPATEN SUMBA TIMUR'],
                        [null, '53', 'KABUPATEN KUPANG'],
                        [null, '53', 'KABUPATEN TIMOR TENGAH SELATAN'],
                        [null, '53', 'KABUPATEN TIMOR TENGAH UTARA'],
                        [null, '53', 'KABUPATEN BELU'],
                        [null, '53', 'KABUPATEN ALOR'],
                        [null, '53', 'KABUPATEN LEMBATA'],
                        [null, '53', 'KABUPATEN FLORES TIMUR'],
                        [null, '53', 'KABUPATEN SIKKA'],
                        [null, '53', 'KABUPATEN ENDE'],
                        [null, '53', 'KABUPATEN NGADA'],
                        [null, '53', 'KABUPATEN MANGGARAI'],
                        [null, '53', 'KABUPATEN ROTE NDAO'],
                        [null, '53', 'KABUPATEN MANGGARAI BARAT'],
                        [null, '53', 'KABUPATEN SUMBA TENGAH'],
                        [null, '53', 'KABUPATEN SUMBA BARAT DAYA'],
                        [null, '53', 'KABUPATEN NAGEKEO'],
                        [null, '53', 'KABUPATEN MANGGARAI TIMUR'],
                        [null, '53', 'KABUPATEN SABU RAIJUA'],
                        [null, '53', 'KABUPATEN MALAKA'],
                        [null, '53', 'KOTA KUPANG'],
                        [null, '61', 'KABUPATEN SAMBAS'],
                        [null, '61', 'KABUPATEN BENGKAYANG'],
                        [null, '61', 'KABUPATEN LANDAK'],
                        [null, '61', 'KABUPATEN MEMPAWAH'],
                        [null, '61', 'KABUPATEN SANGGAU'],
                        [null, '61', 'KABUPATEN KETAPANG'],
                        [null, '61', 'KABUPATEN SINTANG'],
                        [null, '61', 'KABUPATEN KAPUAS HULU'],
                        [null, '61', 'KABUPATEN SEKADAU'],
                        [null, '61', 'KABUPATEN MELAWI'],
                        [null, '61', 'KABUPATEN KAYONG UTARA'],
                        [null, '61', 'KABUPATEN KUBU RAYA'],
                        [null, '61', 'KOTA PONTIANAK'],
                        [null, '61', 'KOTA SINGKAWANG'],
                        [null, '62', 'KABUPATEN KOTAWARINGIN BARAT'],
                        [null, '62', 'KABUPATEN KOTAWARINGIN TIMUR'],
                        [null, '62', 'KABUPATEN KAPUAS'],
                        [null, '62', 'KABUPATEN BARITO SELATAN'],
                        [null, '62', 'KABUPATEN BARITO UTARA'],
                        [null, '62', 'KABUPATEN SUKAMARA'],
                        [null, '62', 'KABUPATEN LAMANDAU'],
                        [null, '62', 'KABUPATEN SERUYAN'],
                        [null, '62', 'KABUPATEN KATINGAN'],
                        [null, '62', 'KABUPATEN PULANG PISAU'],
                        [null, '62', 'KABUPATEN GUNUNG MAS'],
                        [null, '62', 'KABUPATEN BARITO TIMUR'],
                        [null, '62', 'KABUPATEN MURUNG RAYA'],
                        [null, '62', 'KOTA PALANGKA RAYA'],
                        [null, '63', 'KABUPATEN TANAH LAUT'],
                        [null, '63', 'KABUPATEN KOTA BARU'],
                        [null, '63', 'KABUPATEN BANJAR'],
                        [null, '63', 'KABUPATEN BARITO KUALA'],
                        [null, '63', 'KABUPATEN TAPIN'],
                        [null, '63', 'KABUPATEN HULU SUNGAI SELATAN'],
                        [null, '63', 'KABUPATEN HULU SUNGAI TENGAH'],
                        [null, '63', 'KABUPATEN HULU SUNGAI UTARA'],
                        [null, '63', 'KABUPATEN TABALONG'],
                        [null, '63', 'KABUPATEN TANAH BUMBU'],
                        [null, '63', 'KABUPATEN BALANGAN'],
                        [null, '63', 'KOTA BANJARMASIN'],
                        [null, '63', 'KOTA BANJAR BARU'],
                        [null, '64', 'KABUPATEN PASER'],
                        [null, '64', 'KABUPATEN KUTAI BARAT'],
                        [null, '64', 'KABUPATEN KUTAI KARTANEGARA'],
                        [null, '64', 'KABUPATEN KUTAI TIMUR'],
                        [null, '64', 'KABUPATEN BERAU'],
                        [null, '64', 'KABUPATEN PENAJAM PASER UTARA'],
                        [null, '64', 'KABUPATEN MAHAKAM HULU'],
                        [null, '64', 'KOTA BALIKPAPAN'],
                        [null, '64', 'KOTA SAMARINDA'],
                        [null, '64', 'KOTA BONTANG'],
                        [null, '65', 'KABUPATEN MALINAU'],
                        [null, '65', 'KABUPATEN BULUNGAN'],
                        [null, '65', 'KABUPATEN TANA TIDUNG'],
                        [null, '65', 'KABUPATEN NUNUKAN'],
                        [null, '65', 'KOTA TARAKAN'],
                        [null, '71', 'KABUPATEN BOLAANG MONGONDOW'],
                        [null, '71', 'KABUPATEN MINAHASA'],
                        [null, '71', 'KABUPATEN KEPULAUAN SANGIHE'],
                        [null, '71', 'KABUPATEN KEPULAUAN TALAUD'],
                        [null, '71', 'KABUPATEN MINAHASA SELATAN'],
                        [null, '71', 'KABUPATEN MINAHASA UTARA'],
                        [null, '71', 'KABUPATEN BOLAANG MONGONDOW UTARA'],
                        [null, '71', 'KABUPATEN SIAU TAGULANDANG BIARO'],
                        [null, '71', 'KABUPATEN MINAHASA TENGGARA'],
                        [null, '71', 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
                        [null, '71', 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
                        [null, '71', 'KOTA MANADO'],
                        [null, '71', 'KOTA BITUNG'],
                        [null, '71', 'KOTA TOMOHON'],
                        [null, '71', 'KOTA KOTAMOBAGU'],
                        [null, '72', 'KABUPATEN BANGGAI KEPULAUAN'],
                        [null, '72', 'KABUPATEN BANGGAI'],
                        [null, '72', 'KABUPATEN MOROWALI'],
                        [null, '72', 'KABUPATEN POSO'],
                        [null, '72', 'KABUPATEN DONGGALA'],
                        [null, '72', 'KABUPATEN TOLI-TOLI'],
                        [null, '72', 'KABUPATEN BUOL'],
                        [null, '72', 'KABUPATEN PARIGI MOUTONG'],
                        [null, '72', 'KABUPATEN TOJO UNA-UNA'],
                        [null, '72', 'KABUPATEN SIGI'],
                        [null, '72', 'KABUPATEN BANGGAI LAUT'],
                        [null, '72', 'KABUPATEN MOROWALI UTARA'],
                        [null, '72', 'KOTA PALU'],
                        [null, '73', 'KABUPATEN KEPULAUAN SELAYAR'],
                        [null, '73', 'KABUPATEN BULUKUMBA'],
                        [null, '73', 'KABUPATEN BANTAENG'],
                        [null, '73', 'KABUPATEN JENEPONTO'],
                        [null, '73', 'KABUPATEN TAKALAR'],
                        [null, '73', 'KABUPATEN GOWA'],
                        [null, '73', 'KABUPATEN SINJAI'],
                        [null, '73', 'KABUPATEN MAROS'],
                        [null, '73', 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
                        [null, '73', 'KABUPATEN BARRU'],
                        [null, '73', 'KABUPATEN BONE'],
                        [null, '73', 'KABUPATEN SOPPENG'],
                        [null, '73', 'KABUPATEN WAJO'],
                        [null, '73', 'KABUPATEN SIDENRENG RAPPANG'],
                        [null, '73', 'KABUPATEN PINRANG'],
                        [null, '73', 'KABUPATEN ENREKANG'],
                        [null, '73', 'KABUPATEN LUWU'],
                        [null, '73', 'KABUPATEN TANA TORAJA'],
                        [null, '73', 'KABUPATEN LUWU UTARA'],
                        [null, '73', 'KABUPATEN LUWU TIMUR'],
                        [null, '73', 'KABUPATEN TORAJA UTARA'],
                        [null, '73', 'KOTA MAKASSAR'],
                        [null, '73', 'KOTA PAREPARE'],
                        [null, '73', 'KOTA PALOPO'],
                        [null, '74', 'KABUPATEN BUTON'],
                        [null, '74', 'KABUPATEN MUNA'],
                        [null, '74', 'KABUPATEN KONAWE'],
                        [null, '74', 'KABUPATEN KOLAKA'],
                        [null, '74', 'KABUPATEN KONAWE SELATAN'],
                        [null, '74', 'KABUPATEN BOMBANA'],
                        [null, '74', 'KABUPATEN WAKATOBI'],
                        [null, '74', 'KABUPATEN KOLAKA UTARA'],
                        [null, '74', 'KABUPATEN BUTON UTARA'],
                        [null, '74', 'KABUPATEN KONAWE UTARA'],
                        [null, '74', 'KABUPATEN KOLAKA TIMUR'],
                        [null, '74', 'KABUPATEN KONAWE KEPULAUAN'],
                        [null, '74', 'KABUPATEN MUNA BARAT'],
                        [null, '74', 'KABUPATEN BUTON TENGAH'],
                        [null, '74', 'KABUPATEN BUTON SELATAN'],
                        [null, '74', 'KOTA KENDARI'],
                        [null, '74', 'KOTA BAUBAU'],
                        [null, '75', 'KABUPATEN BOALEMO'],
                        [null, '75', 'KABUPATEN GORONTALO'],
                        [null, '75', 'KABUPATEN POHUWATO'],
                        [null, '75', 'KABUPATEN BONE BOLANGO'],
                        [null, '75', 'KABUPATEN GORONTALO UTARA'],
                        [null, '75', 'KOTA GORONTALO'],
                        [null, '76', 'KABUPATEN MAJENE'],
                        [null, '76', 'KABUPATEN POLEWALI MANDAR'],
                        [null, '76', 'KABUPATEN MAMASA'],
                        [null, '76', 'KABUPATEN MAMUJU'],
                        [null, '76', 'KABUPATEN MAMUJU UTARA'],
                        [null, '76', 'KABUPATEN MAMUJU TENGAH'],
                        [null, '81', 'KABUPATEN MALUKU TENGGARA BARAT'],
                        [null, '81', 'KABUPATEN MALUKU TENGGARA'],
                        [null, '81', 'KABUPATEN MALUKU TENGAH'],
                        [null, '81', 'KABUPATEN BURU'],
                        [null, '81', 'KABUPATEN KEPULAUAN ARU'],
                        [null, '81', 'KABUPATEN SERAM BAGIAN BARAT'],
                        [null, '81', 'KABUPATEN SERAM BAGIAN TIMUR'],
                        [null, '81', 'KABUPATEN MALUKU BARAT DAYA'],
                        [null, '81', 'KABUPATEN BURU SELATAN'],
                        [null, '81', 'KOTA AMBON'],
                        [null, '81', 'KOTA TUAL'],
                        [null, '82', 'KABUPATEN HALMAHERA BARAT'],
                        [null, '82', 'KABUPATEN HALMAHERA TENGAH'],
                        [null, '82', 'KABUPATEN KEPULAUAN SULA'],
                        [null, '82', 'KABUPATEN HALMAHERA SELATAN'],
                        [null, '82', 'KABUPATEN HALMAHERA UTARA'],
                        [null, '82', 'KABUPATEN HALMAHERA TIMUR'],
                        [null, '82', 'KABUPATEN PULAU MOROTAI'],
                        [null, '82', 'KABUPATEN PULAU TALIABU'],
                        [null, '82', 'KOTA TERNATE'],
                        [null, '82', 'KOTA TIDORE KEPULAUAN'],
                        [null, '91', 'KABUPATEN FAKFAK'],
                        [null, '91', 'KABUPATEN KAIMANA'],
                        [null, '91', 'KABUPATEN TELUK WONDAMA'],
                        [null, '91', 'KABUPATEN TELUK BINTUNI'],
                        [null, '91', 'KABUPATEN MANOKWARI'],
                        [null, '91', 'KABUPATEN SORONG SELATAN'],
                        [null, '91', 'KABUPATEN SORONG'],
                        [null, '91', 'KABUPATEN RAJA AMPAT'],
                        [null, '91', 'KABUPATEN TAMBRAUW'],
                        [null, '91', 'KABUPATEN MAYBRAT'],
                        [null, '91', 'KABUPATEN MANOKWARI SELATAN'],
                        [null, '91', 'KABUPATEN PEGUNUNGAN ARFAK'],
                        [null, '91', 'KOTA SORONG'],
                        [null, '94', 'KABUPATEN MERAUKE'],
                        [null, '94', 'KABUPATEN JAYAWIJAYA'],
                        [null, '94', 'KABUPATEN JAYAPURA'],
                        [null, '94', 'KABUPATEN NABIRE'],
                        [null, '94', 'KABUPATEN KEPULAUAN YAPEN'],
                        [null, '94', 'KABUPATEN BIAK NUMFOR'],
                        [null, '94', 'KABUPATEN PANIAI'],
                        [null, '94', 'KABUPATEN PUNCAK JAYA'],
                        [null, '94', 'KABUPATEN MIMIKA'],
                        [null, '94', 'KABUPATEN BOVEN DIGOEL'],
                        [null, '94', 'KABUPATEN MAPPI'],
                        [null, '94', 'KABUPATEN ASMAT'],
                        [null, '94', 'KABUPATEN YAHUKIMO'],
                        [null, '94', 'KABUPATEN PEGUNUNGAN BINTANG'],
                        [null, '94', 'KABUPATEN TOLIKARA'],
                        [null, '94', 'KABUPATEN SARMI'],
                        [null, '94', 'KABUPATEN KEEROM'],
                        [null, '94', 'KABUPATEN WAROPEN'],
                        [null, '94', 'KABUPATEN SUPIORI'],
                        [null, '94', 'KABUPATEN MAMBERAMO RAYA'],
                        [null, '94', 'KABUPATEN NDUGA'],
                        [null, '94', 'KABUPATEN LANNY JAYA'],
                        [null, '94', 'KABUPATEN MAMBERAMO TENGAH'],
                        [null, '94', 'KABUPATEN YALIMO'],
                        [null, '94', 'KABUPATEN PUNCAK'],
                        [null, '94', 'KABUPATEN DOGIYAI'],
                        [null, '94', 'KABUPATEN INTAN JAYA'],
                        [null, '94', 'KABUPATEN DEIYAI'],
                        [null, '94', 'KOTA JAYAPURA'],
            ];

	        DB::table('cities')->delete();

	    	foreach($datas as $item){
	        	DB::table('cities')->insert([
                    'province_id' => $item[1],
                    'name' => $item[2],
	        	]);
	    	}
        }
    }
}
